name: CI

on:
  push:
    paths:
      - 'manage-a-bro/**'
  pull_request:
    paths:
      - 'manage-a-bro/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: manage-a-bro

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest tests/
