name: CI - Commitlint on PR (latest commit only)

on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch with full history
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run commitlint on latest commit only
        run: npx commitlint --from=HEAD~1 --to=HEAD
